### PR TITLE
Update to Mbed os 5.11

### PR DESCRIPTION
**Pull request by janjongboom**
@coisme This also significantly brings down RAM usage, and we can actually run this on DISCO-L475VG board now.

### CODE REVIEW

**Review by coisme — APPROVED** [review]
Thank you for augmenting the program! I tried on K64F and it worked. On my DISCO-L475VG-IOT01A with certificate authentication, TLS handshake stopped with unknown error. I guess the reason is lack of RAM.

**Comment by janjongboom** [comment]
@coisme No it should work, but... sometimes the board says that the certificate validity is in the future. So the NTP setting does not always pass through. Resetting the board then is fine again. I'll take a look at it later.

**Comment by janjongboom** [comment]
Note that there is a bug: https://github.com/ARMmbed/wifi-ism43362/issues/42 in cert mode which ST is investigating.

**Comment by coisme** [comment]
@janjongboom I see.

**Pull request merged**
